name: RedditAPI
version: ${project.version}
main: dev.omarathon.redditapi.RedditAPI
api-version: 1.13
authors: [omarathon]
commands:
  redditapi:
    description: Main command for the RedditAPI plugin.
    usage: /redditapi
    permission: redditapi
    aliases: [ra]
