# Please fill in the "" fields with the respective strings, and when you would like the bot to be connectable change connect to true

userAgent:
  platform: ''
  uid: ''
  version: ''
  username: ''

credentials:
  username: ''
  password: ''
  clientID: ''
  clientSecret: ''

connect: false
